# Generated by Django 3.2.8 on 2021-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_title', models.CharField(max_length=1000)),
                ('advertisement_subject', models.CharField(max_length=1000)),
                ('advertisement_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
